keys:
  directory: keys
  prefix: _key

# Settings to authenticate to a Matrix homeserver in order to access the Informo
# network
matrix:
  homeserver: matrix.org
  access_token: ACCESS_TOKEN
  mxid: @acmenews:matrix.org

# Configuration for feeds to poll and parse, and polling interval
feeds:
  - url: "http://www.acmenews.org/feed/"
    identifier: "acmenews"
    poll_interval: 3600

# Database to store poll status. Currently only SQLite3 databases are supported
database:
  path: ./informo-feeder.db
