matrix:
  homeserver: matrix.org
  access_token: ACCESS_TOKEN
  mxid: @acmenews:matrix.org

feeds:
  - url: "http://www.acmenews.org/feed/"
    event_type: "network.informo.news.acmenews"
    poll_interval: 3600

database:
  path: ./rss2informo.db
